export function graphThemeStyles(theme) {
  const dark = theme.mode === "dark";
  const colors = theme.colors;
  return [
    {
      selector: "node",
      style: {
        label: "data(label)",
        "font-family": "Noto Sans, Arial, sans-serif",
        "font-size": 14,
        color: colors.text,
        "text-wrap": "wrap",
        "text-max-width": 135,
        "text-valign": "bottom",
        "text-margin-y": 10,
        "text-outline-color": colors["map-bg"],
        "text-outline-width": 3,
        "background-color": colors.surface,
        "border-width": 3,
        "border-color": "data(color)",
        width: 68,
        height: 68,
      },
    },
    {
      selector: "node.talent",
      style: {
        "background-image": "data(image)",
        shape: "round-rectangle",
        "background-fit": "none",
        "background-width": "data(cropScale)",
        "background-height": "data(cropScaleY)",
        "background-position-x": "data(cropX)",
        "background-position-y": "data(cropY)",
        "background-clip": "node",
        "background-image-crossorigin": "anonymous",
      },
    },
    {
      selector: "node.alum, node.former",
      style: { "border-style": "dashed", "border-color": colors.alumni },
    },
    {
      selector: "node.affiliate",
      style: { "border-color": colors.affiliate, "border-width": 4 },
    },
    {
      selector: "node.unit",
      style: {
        shape: "round-rectangle",
        label: (node) => node.data("label").replace(/([a-z])([A-Z])|([A-Z])([A-Z][a-z])/g, "$1$3\u200b$2$4"),
        width: 110,
        height: 36,
        "font-size": 12,
        "font-weight": 600,
        "text-valign": "center",
        "text-margin-y": 0,
        "text-outline-width": 0,
        "border-width": 1,
        "border-color": colors["unit-line"],
        "background-color": colors["unit-bg"],
        "text-max-width": 90,
        "text-overflow-wrap": "anywhere",
        color: colors["unit-text"] || colors.text,
      },
    },
    {
      selector: "node.cohort",
      style: {
        shape: "round-rectangle",
        "background-color": "data(color)",
        "background-opacity": dark ? 0.10 : 0.25,
        "border-width": 1,
        "border-color": "data(color)",
        "text-valign": "top",
        "text-halign": "left",
        "text-margin-x": 5,
        "text-margin-y": -12,
        "font-size": 19,
        "font-weight": 600,
        padding: 40,
        "text-outline-width": 0,
      },
    },
    {
      selector: "edge",
      style: {
        "curve-style": "bezier",
        "line-color": colors["edge-line"],
        width: 1.7,
        opacity: 0.72,
        "target-arrow-shape": "none",
        label: "data(label)",
        "font-size": 11,
        color: colors["edge-text"],
        "text-background-color": colors["map-bg"],
        "text-background-opacity": 1,
        "text-background-padding": 4,
        "text-rotation": "autorotate",
      },
    },
    { selector: "edge.membership", style: { "line-style": "dotted" } },
    {
      selector: "edge.duo",
      style: {
        "text-margin-y": "data(labelOffset)",
        width: 2.7,
        "line-color": colors.duo,
        color: colors["duo-text"],
        opacity: 0.9,
      },
    },
    {
      selector: ".picked",
      style: {
        "overlay-color": colors.overlay,
        "overlay-padding": 8,
        "overlay-opacity": 0.12,
      },
    },
    { selector: "edge.picked", style: { width: 4, opacity: 1 } },
  ];
}
